version: "3.7"

services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-envoy
    ports:
      - "8091:8080"
    depends_on:
      - time-server
    networks:
      - backend

  time-server:
    build:
      context: ./time
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-time
    env_file:
      - .env
    ports:
      - "9090:9090"
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-frontend
    ports:
      - "3000:80"
    networks:
      - backend

networks:
  backend:
