version: "3.7"
services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-envoy
    ports:
      - "8079:8080"
    links:
      - time-server
    networks:
      - backend

  time-server:
    build:
      context: ./time
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-time
    ports:
      - "9090:9090"
    networks:
      - backend

networks:
  backend:
